# Generated by Django 4.2.26 on 2025-12-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCounters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num_count', models.PositiveIntegerField(default=0)),
                ('cataloge_num_count', models.PositiveIntegerField(default=0)),
                ('main_page_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
