# Generated by Django 4.2.26 on 2025-12-07 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveIntegerField(unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_service_type', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=128)),
                ('email_add', models.CharField(max_length=128)),
                ('cell_num', models.CharField(max_length=128)),
                ('street_name', models.CharField(max_length=128)),
                ('house_num', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('invoice_num', models.PositiveIntegerField(unique=True)),
                ('order_status', models.CharField(choices=[('PENDING', 'pending'), ('DELIVERED', 'delivered')], default='PENDING', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('partNum', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
    ]
