# Generated by Django 4.2.26 on 2025-12-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email_add',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
