# Generated by Django 4.2.26 on 2025-12-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_cell_num_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
