# Generated by Django 4.2.26 on 2025-12-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stage',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
